name: Auto Generate JSON
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
# Ye robot tab chalega jab in folders mein kuch naya aayega, YA jab aap manually button dabayenge
on:
  push:
    branches:
      - main
    paths:
      - 'Status/**'
      - 'RadhaKrishna/**'
      - 'Others/**'
      - 'Radha/**'
      - 'Krishna/**'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # <--- ⭐ v3 se v4 kar diya

      - name: Setup Python
        uses: actions/setup-python@v5 # <--- ⭐ v4 se v5 kar diya
        with:
          python-version: '3.x'

      - name: Run JSON Generator Script
        run: python generate_json.py

      - name: Commit and Push New JSON
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add wallpapers.json
          git commit -m "Auto-generated wallpapers.json by Robot" || echo "No changes to commit"
          git push
